In [1]:
#q1
try:
    z=5/0
    
except ZeroDivisionError as error:
        # Output expected ZeroDivisionErrors.
        print(error)


division by zero


In [17]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
final=[i+" "+j+" "+z for i in subjects for j in verbs for z in objects]
for i in final:
    print(i)
    

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [15]:
#q3
import numpy as np
def matrix(vector, n,n1):
    
    if n1=='dec':
        final= np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(5,5)
    elif n1== 'inc':
        final = np.array([x**i for x in vector for i in range(n)]).reshape(5,5)
    
    return final
vector=(1,2,3,4,5)
n=5
print("Increasing order: \n",matrix(vector,n,'inc'))
print("Increasing order: \n",matrix(vector,n,'dec'))

Increasing order: 
 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
Increasing order: 
 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
